### ISSUE TITLE
Help make add-ons multiprocess compatible with Add-on Compatibility Reporter

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#99]
https://blog.mozilla.org/addons/2016/09/07/help-make-add-ons-multiprocess-compatible-with-add-on-compatibility-reporter/

**Comment by siclemx** [comment]
Hola Jorge tomaré este articulo, saludos!

**Comment by jvillalobos** [comment]
@BoSicle Como va la traducción de este artículo?

**Comment by siclemx** [comment]
Hola, lo termino ya este fin de semana. Disculpen la demora.

Saludos
Uriel

On 12 Dec 2016 8:08 a.m., "Jorge Villalobos" <notifications@github.com>
wrote:

@BoSicle <https://github.com/BoSicle> Como va la traducción de este
artículo?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mozillahispano/blog-labs/issues/99#issuecomment-266439457>,
or mute the thread

**Comment by siclemx** [comment]
Listo, disculpen la demora  :)

https://docs.google.com/document/d/1ISTm_ithW_EftC9r5ajQ0jqyVmMCIjLy9TRbc5fxDJ0/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/ayuda-al-firefox-multiproceso-con-add-on-compatibility-reporter/

Gracias!
